package co.schmitt.si.db;

/**
 * User: pschmitt
 * Date: 8/11/13
 * Time: 3:58 PM
 */
final class DBQueries {
    protected static final String SQL_HALT = "SHUTDOWN";
    protected static final String SQL_DETAILS = "SELECT COURSE_DESCRIPTION.COURSE_NAME, COURSE_DESCRIPTION.COURSE_DESCRIPTION, " +
            "DATES.WEEKDAY, DATES.START_TIME, DATES.END_TIME, FEES.FEES, LOCATION.LOCATION, " +
            "PARTICIPANTS.MAX_PARTICIPANTS, PARTICIPANTS.MIN_PARTICIPANTS FROM COURSE_DESCRIPTION " +
            "INNER JOIN FEES ON FEES.DESCRIPTION_ID = COURSE_DESCRIPTION.DESCRIPTION_ID " +
            "INNER JOIN LOCATION ON LOCATION.COURSE_ID = COURSE_DESCRIPTION.COURSE_ID " +
            "INNER JOIN PARTICIPANTS ON PARTICIPANTS.COURSE_DESCRIPTION_ID = COURSE_DESCRIPTION.DESCRIPTION_ID " +
            "INNER JOIN DATES ON DATES.DESCRIPTION_ID = COURSE_DESCRIPTION.DESCRIPTION_ID " +
            "WHERE COURSE_DESCRIPTION.COURSE_NAME = ?";
    protected static final String SQL_DETAIL_LEGACY = "SELECT KURS.NAME, KURS.GEBUEHREN, KURS.MIN_TEILNEHMER, KURS.MAX_TEILNEHMER, " +
            "KURS.TEILNEHMERANZAHL, TERMIN.WOCHENTAG, TERMIN.UHRZEIT_VON, TERMIN.UHRZEIT_BIS FROM KURS " +
            "INNER JOIN KURS_TERMIN ON KURS_TERMIN.KURS_ID = KURS.ID " +
            "INNER JOIN TERMIN ON TERMIN.ID = KURS_TERMIN.TERMIN_ID " +
            "WHERE KURS.NAME = ?";

    private DBQueries() {}
}
